name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Obtiene todo el historial de Git
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necesario para hacer push de tags
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Obtiene todo el historial de Git
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@Asorjs'  # Si tu paquete tiene un scope
      - name: Configure Git for Merge
        run: git config pull.rebase false  # O puedes usar true para rebase
      - run: npm ci
      - name: Increment version
        run: npm version patch -m "Upgrade to %s [skip ci]"
      - name: Push changes and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:main --tags
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
