name: Publish to npm

on:
  push:
    branches:
      - main  # o el nombre de tu rama principal

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20  # o la versión que uses
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build  # asegúrate de tener un script de build en tu package.json
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_KEY }}